/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param address Address of company's headquarter.
 * @param city City of company's headquarter.
 * @param country Country of company's headquarter.
 * @param currency Currency used in company filings.
 * @param cusip CUSIP number.
 * @param sedol Sedol number.
 * @param description Company business summary.
 * @param exchange Listed exchange.
 * @param ggroup GICS industry group.
 * @param gind GICS industry.
 * @param gsector GICS sector.
 * @param gsubind GICS sub-industry.
 * @param isin ISIN number.
 * @param naicsNationalIndustry NAICS national industry.
 * @param naics NAICS industry.
 * @param naicsSector NAICS sector.
 * @param naicsSubsector NAICS subsector.
 * @param name Company name.
 * @param phone Company phone number.
 * @param state State of company's headquarter.
 * @param ticker Company symbol/ticker as used on the listed exchange.
 * @param weburl Company website.
 * @param ipo IPO date.
 * @param marketCapitalization Market Capitalization.
 * @param shareOutstanding Number of oustanding shares.
 * @param employeeTotal Number of employee.
 * @param logo Logo image.
 * @param finnhubIndustry Finnhub industry classification.
 */

@Serializable
data class CompanyProfile (
    /* Address of company's headquarter. */
    @SerialName("address")
    val address: String? = null,
    /* City of company's headquarter. */
    @SerialName("city")
    val city: String? = null,
    /* Country of company's headquarter. */
    @SerialName("country")
    val country: String? = null,
    /* Currency used in company filings. */
    @SerialName("currency")
    val currency: String? = null,
    /* CUSIP number. */
    @SerialName("cusip")
    val cusip: String? = null,
    /* Sedol number. */
    @SerialName("sedol")
    val sedol: String? = null,
    /* Company business summary. */
    @SerialName("description")
    val description: String? = null,
    /* Listed exchange. */
    @SerialName("exchange")
    val exchange: String? = null,
    /* GICS industry group. */
    @SerialName("ggroup")
    val ggroup: String? = null,
    /* GICS industry. */
    @SerialName("gind")
    val gind: String? = null,
    /* GICS sector. */
    @SerialName("gsector")
    val gsector: String? = null,
    /* GICS sub-industry. */
    @SerialName("gsubind")
    val gsubind: String? = null,
    /* ISIN number. */
    @SerialName("isin")
    val isin: String? = null,
    /* NAICS national industry. */
    @SerialName("naicsNationalIndustry")
    val naicsNationalIndustry: String? = null,
    /* NAICS industry. */
    @SerialName("naics")
    val naics: String? = null,
    /* NAICS sector. */
    @SerialName("naicsSector")
    val naicsSector: String? = null,
    /* NAICS subsector. */
    @SerialName("naicsSubsector")
    val naicsSubsector: String? = null,
    /* Company name. */
    @SerialName("name")
    val name: String? = null,
    /* Company phone number. */
    @SerialName("phone")
    val phone: String? = null,
    /* State of company's headquarter. */
    @SerialName("state")
    val state: String? = null,
    /* Company symbol/ticker as used on the listed exchange. */
    @SerialName("ticker")
    val ticker: String? = null,
    /* Company website. */
    @SerialName("weburl")
    val weburl: String? = null,
    /* IPO date. */
    @SerialName("ipo")
    val ipo: String? = null,
    /* Market Capitalization. */
    @SerialName("marketCapitalization")
    val marketCapitalization: Float? = null,
    /* Number of oustanding shares. */
    @SerialName("shareOutstanding")
    val shareOutstanding: Float? = null,
    /* Number of employee. */
    @SerialName("employeeTotal")
    val employeeTotal: String? = null, // backend can return the result "wastage", necessary to parse as String to avoid crashes
    /* Logo image. */
    @SerialName("logo")
    val logo: String? = null,
    /* Finnhub industry classification. */
    @SerialName("finnhubIndustry")
    val finnhubIndustry: String? = null
) {
	companion object {
    }

}

