/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable
/**
 * 
 * @param articlesInLastWeek 
 * @param buzz 
 * @param weeklyAverage 
 */

data class CompanyNewsStatistics (
    /*  */
    @Json(name = "articlesInLastWeek")
    val articlesInLastWeek: kotlin.Long? = null,
    /*  */
    @Json(name = "buzz")
    val buzz: kotlin.Float? = null,
    /*  */
    @Json(name = "weeklyAverage")
    val weeklyAverage: kotlin.Float? = null
) : Serializable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

