/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param country Country name
 * @param code2 Alpha 2 code
 * @param code3 Alpha 3 code
 * @param codeNo UN code
 * @param currency Currency name
 * @param currencyCode Currency code
 */

@Serializable
data class CountryMetadata (
    /* Country name */
    @SerialName("country")
    val country: String? = null,
    /* Alpha 2 code */
    @SerialName("code2")
    val code2: String? = null,
    /* Alpha 3 code */
    @SerialName("code3")
    val code3: String? = null,
    /* UN code */
    @SerialName("codeNo")
    val codeNo: String? = null,
    /* Currency name */
    @SerialName("currency")
    val currency: String? = null,
    /* Currency code */
    @SerialName("currencyCode")
    val currencyCode: String? = null
) {
	companion object {
    }

}

