/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param state State.
 * @param case Number of confirmed cases.
 * @param death Number of confirmed deaths.
 * @param updated Updated time.
 */

@Serializable
data class CovidInfo (
    /* State. */
    @SerialName("state")
    val state: String? = null,
    /* Number of confirmed cases. */
    @SerialName("case")
    val case: Float? = null,
    /* Number of confirmed deaths. */
    @SerialName("death")
    val death: Float? = null,
    /* Updated time. */
    @SerialName("updated")
    val updated: String? = null
) {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

