/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param description Symbol description
 * @param displaySymbol Display symbol name.
 * @param symbol Unique symbol used to identify this symbol used in <code>/crypto/candle</code> endpoint.
 */

@Serializable
data class CryptoSymbol (
    /* Symbol description */
    @SerialName("description")
    val description: String? = null,
    /* Display symbol name. */
    @SerialName("displaySymbol")
    val displaySymbol: String? = null,
    /* Unique symbol used to identify this symbol used in <code>/crypto/candle</code> endpoint. */
    @SerialName("symbol")
    val symbol: String? = null
) {
	companion object {
    }

}

