/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param actual Actual earning result.
 * @param estimate Estimated earning.
 * @param period Reported period.
 * @param symbol Company symbol.
 */

@Serializable
data class EarningResult (
    /* Actual earning result. */
    @SerialName("actual")
    val actual: Float? = null,
    /* Estimated earning. */
    @SerialName("estimate")
    val estimate: Float? = null,
    /* Reported period. */
    @SerialName("period")
    val period: String? = null,
    /* Company symbol. */
    @SerialName("symbol")
    val symbol: String? = null
) {
	companion object {
    }

}

