/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param epsAvg Average EPS estimates.
 * @param epsHigh Highest estimate.
 * @param epsLow Lowest estimate.
 * @param numberAnalysts Number of Analysts.
 * @param period Period.
 */

@Serializable
data class EarningEstimate (
    /* Average EPS estimates. */
    @SerialName("epsAvg")
    val epsAvg: kotlin.Float? = null,
    /* Highest estimate. */
    @SerialName("epsHigh")
    val epsHigh: kotlin.Float? = null,
    /* Lowest estimate. */
    @SerialName("epsLow")
    val epsLow: kotlin.Float? = null,
    /* Number of Analysts. */
    @SerialName("numberAnalysts")
    val numberAnalysts: kotlin.Long? = null,
    /* Period. */
    @SerialName("period")
    val period: kotlin.String? = null
)
