/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable
/**
 * 
 * @param symbol Symbol.
 * @param date Date.
 * @param hour Indicates whether the earnings is announced before market open(<code>bmo</code>), after market close(<code>amc</code>), or during market hour(<code>dmh</code>).
 * @param year Earnings year.
 * @param quarter Earnings quarter.
 * @param epsEstimate EPS estimate.
 * @param epsActual EPS actual.
 * @param revenueEstimate Revenue estimate.
 * @param revenueActual Revenue actual.
 */

data class EarningRelease (
    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Date. */
    @Json(name = "date")
    val date: kotlin.String? = null,
    /* Indicates whether the earnings is announced before market open(<code>bmo</code>), after market close(<code>amc</code>), or during market hour(<code>dmh</code>). */
    @Json(name = "hour")
    val hour: kotlin.String? = null,
    /* Earnings year. */
    @Json(name = "year")
    val year: kotlin.Long? = null,
    /* Earnings quarter. */
    @Json(name = "quarter")
    val quarter: kotlin.Long? = null,
    /* EPS estimate. */
    @Json(name = "epsEstimate")
    val epsEstimate: kotlin.Float? = null,
    /* EPS actual. */
    @Json(name = "epsActual")
    val epsActual: kotlin.Float? = null,
    /* Revenue estimate. */
    @Json(name = "revenueEstimate")
    val revenueEstimate: kotlin.Long? = null,
    /* Revenue actual. */
    @Json(name = "revenueActual")
    val revenueActual: kotlin.Long? = null
) : Serializable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

