/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.finnhub.api.models


import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 *
 * @param data List of estimates
 * @param freq Frequency: annual or quarterly.
 * @param symbol Company symbol.
 */

@ExperimentalSerializationApi
@Serializable
data class EarningsEstimates(
    /* List of estimates */
    @SerialName("data")
    val data: List<JsonObject>? = null,
    /* Frequency: annual or quarterly. */
    @SerialName("freq")
    val freq: String? = null,
    /* Company symbol. */
    @SerialName("symbol")
    val symbol: String? = null
) {
    companion object {
    }

}

