/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param symbol Symbol.
 * @param date Date.
 * @param hour Indicates whether the earnings is announced before market open(<code>bmo</code>), after market close(<code>amc</code>), or during market hour(<code>dmh</code>).
 * @param year Earnings year.
 * @param quarter Earnings quarter.
 * @param epsEstimate EPS estimate.
 * @param epsActual EPS actual.
 * @param revenueEstimate Revenue estimate.
 * @param revenueActual Revenue actual.
 */

@Serializable
data class EarningRelease (
    /* Symbol. */
    @SerialName("symbol")
    val symbol: kotlin.String? = null,
    /* Date. */
    @SerialName("date")
    val date: kotlin.String? = null,
    /* Indicates whether the earnings is announced before market open(<code>bmo</code>), after market close(<code>amc</code>), or during market hour(<code>dmh</code>). */
    @SerialName("hour")
    val hour: kotlin.String? = null,
    /* Earnings year. */
    @SerialName("year")
    val year: kotlin.Long? = null,
    /* Earnings quarter. */
    @SerialName("quarter")
    val quarter: kotlin.Long? = null,
    /* EPS estimate. */
    @SerialName("epsEstimate")
    val epsEstimate: kotlin.Float? = null,
    /* EPS actual. */
    @SerialName("epsActual")
    val epsActual: kotlin.Float? = null,
    /* Revenue estimate. */
    @SerialName("revenueEstimate")
    val revenueEstimate: kotlin.Long? = null,
    /* Revenue actual. */
    @SerialName("revenueActual")
    val revenueActual: kotlin.Long? = null
)

