/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * 
 * @param symbol Company symbol.
 * @param transcript Transcript content.
 * @param participant Participant list
 * @param audio Audio link.
 * @param id Transcript's ID.
 * @param title Title.
 * @param time Time of the event.
 * @param year Year of earnings result in the case of earnings call transcript.
 * @param quarter Quarter of earnings result in the case of earnings call transcript.
 */

@Serializable
data class EarningsCallTranscripts (
    /* Company symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* Transcript content. */
    @SerialName("transcript")
    val transcript: List<JsonObject>? = null,
    /* Participant list */
    @SerialName("participant")
    val participant: List<JsonObject>? = null,
    /* Audio link. */
    @SerialName("audio")
    val audio: String? = null,
    /* Transcript's ID. */
    @SerialName("id")
    val id: String? = null,
    /* Title. */
    @SerialName("title")
    val title: String? = null,
    /* Time of the event. */
    @SerialName("time")
    val time: String? = null,
    /* Year of earnings result in the case of earnings call transcript. */
    @SerialName("year")
    val year: Long? = null,
    /* Quarter of earnings result in the case of earnings call transcript. */
    @SerialName("quarter")
    val quarter: Long? = null
) {
	companion object {
		private const val serialVersionUID: Long = 123
	}
}

