/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable
/**
 * 
 * @param revenueAvg Average revenue estimates.
 * @param revenueHigh Highest estimate.
 * @param revenueLow Lowest estimate.
 * @param numberAnalysts Number of Analysts.
 * @param period Period.
 */

data class Estimate (
    /* Average revenue estimates. */
    @Json(name = "revenueAvg")
    val revenueAvg: kotlin.Long? = null,
    /* Highest estimate. */
    @Json(name = "revenueHigh")
    val revenueHigh: kotlin.Long? = null,
    /* Lowest estimate. */
    @Json(name = "revenueLow")
    val revenueLow: kotlin.Long? = null,
    /* Number of Analysts. */
    @Json(name = "numberAnalysts")
    val numberAnalysts: kotlin.Long? = null,
    /* Period. */
    @Json(name = "period")
    val period: kotlin.String? = null
) : Serializable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

