/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable
/**
 * 
 * @param symbol Symbol description
 * @param share Number of shares owned by the ETF.
 * @param percent Portfolio's percent
 */

data class ETFHoldingsData (
    /* Symbol description */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Number of shares owned by the ETF. */
    @Json(name = "share")
    val share: kotlin.Float? = null,
    /* Portfolio's percent */
    @Json(name = "percent")
    val percent: kotlin.Float? = null
) : Serializable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

