/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param accessNumber Access number.
 * @param symbol Symbol.
 * @param cik CIK.
 * @param form Form type.
 * @param filedDate Filed date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param acceptedDate Accepted date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param reportUrl Report's URL.
 * @param filingUrl Filing's URL.
 */

@Serializable
data class Filing (
    /* Access number. */
    @SerialName("accessNumber")
    val accessNumber: String? = null,
    /* Symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* CIK. */
    @SerialName("cik")
    val cik: String? = null,
    /* Form type. */
    @SerialName("form")
    val form: String? = null,
    /* Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
    @SerialName("filedDate")
    val filedDate: String? = null,
    /* Accepted date <code>%Y-%m-%d %H:%M:%S</code>. */
    @SerialName("acceptedDate")
    val acceptedDate: String? = null,
    /* Report's URL. */
    @SerialName("reportUrl")
    val reportUrl: String? = null,
    /* Filing's URL. */
    @SerialName("filingUrl")
    val filingUrl: String? = null
) {
	companion object {
    }

}

