/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable
/**
 * 
 * @param accessNumber Access number.
 * @param symbol Symbol.
 * @param cik CIK.
 * @param form Form type.
 * @param filedDate Filed date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param acceptedDate Accepted date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param reportUrl Report's URL.
 * @param filingUrl Filing's URL.
 */

data class Filing (
    /* Access number. */
    @Json(name = "accessNumber")
    val accessNumber: kotlin.String? = null,
    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* CIK. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,
    /* Form type. */
    @Json(name = "form")
    val form: kotlin.String? = null,
    /* Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "filedDate")
    val filedDate: java.time.OffsetDateTime? = null,
    /* Accepted date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "acceptedDate")
    val acceptedDate: java.time.OffsetDateTime? = null,
    /* Report's URL. */
    @Json(name = "reportUrl")
    val reportUrl: kotlin.String? = null,
    /* Filing's URL. */
    @Json(name = "filingUrl")
    val filingUrl: kotlin.String? = null
) : Serializable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

