/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable
/**
 * 
 * @param o List of open prices for returned candles.
 * @param h List of high prices for returned candles.
 * @param l List of low prices for returned candles.
 * @param c List of close prices for returned candles.
 * @param v List of volume data for returned candles.
 * @param t List of timestamp for returned candles.
 * @param s Status of the response. This field can either be ok or no_data.
 */

data class ForexCandles (
    /* List of open prices for returned candles. */
    @Json(name = "o")
    val o: kotlin.Array<kotlin.Float>? = null,
    /* List of high prices for returned candles. */
    @Json(name = "h")
    val h: kotlin.Array<kotlin.Float>? = null,
    /* List of low prices for returned candles. */
    @Json(name = "l")
    val l: kotlin.Array<kotlin.Float>? = null,
    /* List of close prices for returned candles. */
    @Json(name = "c")
    val c: kotlin.Array<kotlin.Float>? = null,
    /* List of volume data for returned candles. */
    @Json(name = "v")
    val v: kotlin.Array<kotlin.Float>? = null,
    /* List of timestamp for returned candles. */
    @Json(name = "t")
    val t: kotlin.Array<kotlin.Float>? = null,
    /* Status of the response. This field can either be ok or no_data. */
    @Json(name = "s")
    val s: kotlin.String? = null
) : Serializable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

