/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param symbol Symbol
 * @param action <code>add</code> or <code>remove</code>.
 * @param date Date of joining or leaving the index.
 */

@Serializable
data class IndexHistoricalConstituent (
    /* Symbol */
    @SerialName("symbol")
    val symbol: kotlin.String? = null,
    /* <code>add</code> or <code>remove</code>. */
    @SerialName("action")
    val action: kotlin.String? = null,
    /* Date of joining or leaving the index. */
    @SerialName("date")
    val date: kotlin.String? = null
)

