/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param symbol Index's symbol.
 * @param constituents Array of constituents.
 */

@Serializable
data class IndicesConstituents (
    /* Index's symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* Array of constituents. */
    @SerialName("constituents")
    val constituents: List<String>? = null
) {
	companion object {
    }

}

