/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param name Investor's name.
 * @param share Number of shares held by the investor.
 * @param change Number of share changed (net buy or sell) from the last period.
 * @param filingDate Filing date.
 */

@Serializable
data class Investor (
    /* Investor's name. */
    @SerialName("name")
    val name: kotlin.String? = null,
    /* Number of shares held by the investor. */
    @SerialName("share")
    val share: kotlin.Long? = null,
    /* Number of share changed (net buy or sell) from the last period. */
    @SerialName("change")
    val change: kotlin.Long? = null,
    /* Filing date. */
    @SerialName("filingDate")
    val filingDate: kotlin.String? = null
)

