/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 * @param symbol Symbol.
 * @param date IPO date.
 * @param exchange Exchange.
 * @param name Company's name.
 * @param status IPO status. Can take 1 of the following values: <code>expected</code>,<code>priced</code>,<code>withdrawn</code>,<code>filed</code>
 * @param price Projected price or price range.
 * @param numberOfShares Number of shares offered during the IPO.
 * @param totalSharesValue Total shares value.
 */

@Serializable
data class IPOEvent (
    /* Symbol. */
    @SerialName("symbol")
    val symbol: kotlin.String? = null,
    /* IPO date. */
    @SerialName("date")
    val date: kotlin.String? = null,
    /* Exchange. */
    @SerialName("exchange")
    val exchange: kotlin.String? = null,
    /* Company's name. */
    @SerialName("name")
    val name: kotlin.String? = null,
    /* IPO status. Can take 1 of the following values: <code>expected</code>,<code>priced</code>,<code>withdrawn</code>,<code>filed</code> */
    @SerialName("status")
    val status: kotlin.String? = null,
    /* Projected price or price range. */
    @SerialName("price")
    val price: kotlin.String? = null,
    /* Number of shares offered during the IPO. */
    @SerialName("numberOfShares")
    val numberOfShares: kotlin.Long? = null,
    /* Total shares value. */
    @SerialName("totalSharesValue")
    val totalSharesValue: kotlin.Long? = null
)
