/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param b Bid price.
 * @param a Ask price.
 * @param bv Bid volume.
 * @param av Ask volume.
 * @param t Reference UNIX timestamp in ms.
 */

@Serializable
data class LastBidMinusAsk (
    /* Bid price. */
    @SerialName("b")
    val b: Float? = null,
    /* Ask price. */
    @SerialName("a")
    val a: Float? = null,
    /* Bid volume. */
    @SerialName("bv")
    val bv: Float? = null,
    /* Ask volume. */
    @SerialName("av")
    val av: Float? = null,
    /* Reference UNIX timestamp in ms. */
    @SerialName("t")
    val t: Long? = null
) {
	companion object {
    }

}

