/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param category News category.
 * @param datetime Published time in UNIX timestamp.
 * @param headline News headline.
 * @param id News ID. This value can be used for <code>minId</code> params to get the latest news only.
 * @param image Thumbnail image URL.
 * @param related Related stocks and companies mentioned in the article.
 * @param source News source.
 * @param summary News summary.
 * @param url URL of the original article.
 */

@Serializable
data class News (
    /* News category. */
    @SerialName("category")
    val category: String? = null,
    /* Published time in UNIX timestamp. */
    @SerialName("datetime")
    val datetime: Long? = null,
    /* News headline. */
    @SerialName("headline")
    val headline: String? = null,
    /* News ID. This value can be used for <code>minId</code> params to get the latest news only. */
    @SerialName("id")
    val id: Long? = null,
    /* Thumbnail image URL. */
    @SerialName("image")
    val image: String? = null,
    /* Related stocks and companies mentioned in the article. */
    @SerialName("related")
    val related: String? = null,
    /* News source. */
    @SerialName("source")
    val source: String? = null,
    /* News summary. */
    @SerialName("summary")
    val summary: String? = null,
    /* URL of the original article. */
    @SerialName("url")
    val url: String? = null
) {
	companion object {
    }

}

