/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param o Open price of the day
 * @param h High price of the day
 * @param l Low price of the day
 * @param c Current price
 * @param pc Previous close price
 */

@Serializable
data class Quote (
    /* Open price of the day */
    @SerialName("o")
    val o: Float? = null,
    /* High price of the day */
    @SerialName("h")
    val h: Float? = null,
    /* Low price of the day */
    @SerialName("l")
    val l: Float? = null,
    /* Current price */
    @SerialName("c")
    val c: Float? = null,
    /* Previous close price */
    @SerialName("pc")
    val pc: Float? = null
) {
	companion object {
    }

}

