/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * 
 * @param symbol Symbol.
 * @param cik CIK.
 * @param similarity Array of filings with its cosine similarity compared to the same report of the previous year.
 */

@Serializable
data class SimilarityIndex (
    /* Symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* CIK. */
    @SerialName("cik")
    val cik: String? = null,
    /* Array of filings with its cosine similarity compared to the same report of the previous year. */
    @SerialName("similarity")
    val similarity: List<JsonObject>? = null
) {
	companion object {
    }

}

