/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param symbol Symbol.
 * @param date Split date.
 * @param fromFactor From factor.
 * @param toFactor To factor.
 */

@Serializable
data class Split (
    /* Symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* Split date. */
    @SerialName("date")
    val date: String? = null,
    /* From factor. */
    @SerialName("fromFactor")
    val fromFactor: Float? = null,
    /* To factor. */
    @SerialName("toFactor")
    val toFactor: Float? = null
) {
	companion object {
    }

}

