/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param s Symbol.
 * @param skip Number of ticks skipped.
 * @param count Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
 * @param total Total number of ticks for that date.
 * @param v List of volume data.
 * @param p List of price data.
 * @param t List of timestamp in UNIX ms.
 * @param x List of venues/exchanges.
 */

@Serializable
data class TickData (
    /* Symbol. */
    @SerialName("s")
    val s: String? = null,
    /* Number of ticks skipped. */
    @SerialName("skip")
    val skip: Long? = null,
    /* Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned. */
    @SerialName("count")
    val count: Long? = null,
    /* Total number of ticks for that date. */
    @SerialName("total")
    val total: Long? = null,
    /* List of volume data. */
    @SerialName("v")
    val v: List<Float>? = null,
    /* List of price data. */
    @SerialName("p")
    val p: List<Float>? = null,
    /* List of timestamp in UNIX ms. */
    @SerialName("t")
    val t: List<Long>? = null,
    /* List of venues/exchanges. */
    @SerialName("x")
    val x: List<String>? = null
) {
	companion object {
    }

}

