/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable
/**
 * 
 * @param name Speaker's name
 * @param speech Speaker's speech
 */

data class TranscriptContent (
    /* Speaker's name */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* Speaker's speech */
    @Json(name = "speech")
    val speech: kotlin.Array<kotlin.String>? = null
) : Serializable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

