/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.finnhub.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param name Participant's name
 * @param description Participant's description
 */

@Serializable
data class TranscriptParticipant (
    /* Participant's name */
    @SerialName("name")
    val name: kotlin.String? = null,
    /* Participant's description */
    @SerialName("description")
    val description: kotlin.String? = null
)

