/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.AIChatMessage

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param messages Messages
 * @param stream Stream responses
 */

data class AIChatBody (

    /* Messages */
    @Json(name = "messages")
    val messages: kotlin.collections.List<AIChatMessage>,

    /* Stream responses */
    @Json(name = "stream")
    val stream: kotlin.Boolean? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

