/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param chatId Chat ID.
 * @param content Response text.
 * @param querySummary Query summary
 * @param relatedQueries Related queries.
 * @param tickers List of tickers mentioned.
 * @param sources Sources.
 * @param widgets Widgets.
 */

data class AIChatResponse (

    /* Chat ID. */
    @Json(name = "chatId")
    val chatId: kotlin.String? = null,

    /* Response text. */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /* Query summary */
    @Json(name = "querySummary")
    val querySummary: kotlin.String? = null,

    /* Related queries. */
    @Json(name = "relatedQueries")
    val relatedQueries: kotlin.collections.List<kotlin.Any>? = null,

    /* List of tickers mentioned. */
    @Json(name = "tickers")
    val tickers: kotlin.collections.List<kotlin.Any>? = null,

    /* Sources. */
    @Json(name = "sources")
    val sources: kotlin.collections.List<kotlin.Any>? = null,

    /* Widgets. */
    @Json(name = "widgets")
    val widgets: kotlin.collections.List<kotlin.Any>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

