/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param date Date
 * @param priceIndex Price Index
 * @param dailyAvgPrice Daily average ticket price.
 */

data class AirlinePriceIndex (

    /* Date */
    @Json(name = "date")
    val date: kotlin.String? = null,

    /* Price Index */
    @Json(name = "priceIndex")
    val priceIndex: kotlin.Float? = null,

    /* Daily average ticket price. */
    @Json(name = "dailyAvgPrice")
    val dailyAvgPrice: kotlin.Float? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

