/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.AirlinePriceIndex

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param `data` Array of price index.
 * @param airline Airline name
 * @param from From date
 * @param to To date
 */

data class AirlinePriceIndexData (

    /* Array of price index. */
    @Json(name = "data")
    val `data`: kotlin.collections.List<AirlinePriceIndex>? = null,

    /* Airline name */
    @Json(name = "airline")
    val airline: kotlin.String? = null,

    /* From date */
    @Json(name = "from")
    val from: kotlin.String? = null,

    /* To date */
    @Json(name = "to")
    val to: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

