/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param branchId Branch ID
 * @param address Branch address
 * @param state State
 * @param zipCode  Zip code
 * @param date Date opened
 */

data class BankBranchData (

    /* Branch ID */
    @Json(name = "branchId")
    val branchId: kotlin.String? = null,

    /* Branch address */
    @Json(name = "address")
    val address: kotlin.String? = null,

    /* State */
    @Json(name = "state")
    val state: kotlin.String? = null,

    /*  Zip code */
    @Json(name = "zipCode")
    val zipCode: kotlin.String? = null,

    /* Date opened */
    @Json(name = "date")
    val date: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

