/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param c List of close prices for returned candles.
 * @param t List of timestamp for returned candles.
 * @param s Status of the response. This field can either be ok or no_data.
 */

data class BondCandles (

    /* List of close prices for returned candles. */
    @Json(name = "c")
    val c: kotlin.collections.List<kotlin.Float>? = null,

    /* List of timestamp for returned candles. */
    @Json(name = "t")
    val t: kotlin.collections.List<kotlin.Long>? = null,

    /* Status of the response. This field can either be ok or no_data. */
    @Json(name = "s")
    val s: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

