/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param skip Number of ticks skipped.
 * @param count Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
 * @param total Total number of ticks for that date.
 * @param v List of volume data.
 * @param p List of price data.
 * @param t List of timestamp in UNIX ms.
 * @param si List of values showing the side (Buy/sell) of each trade. List of supported values: <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\",>here</a>
 * @param cp List of values showing the counterparty of each trade. List of supported values: <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\",>here</a>
 * @param c List of trade conditions. A comprehensive list of trade conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\">here</a>
 */

data class BondTickData (

    /* Number of ticks skipped. */
    @Json(name = "skip")
    val skip: kotlin.Long? = null,

    /* Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned. */
    @Json(name = "count")
    val count: kotlin.Long? = null,

    /* Total number of ticks for that date. */
    @Json(name = "total")
    val total: kotlin.Long? = null,

    /* List of volume data. */
    @Json(name = "v")
    val v: kotlin.collections.List<kotlin.Float>? = null,

    /* List of price data. */
    @Json(name = "p")
    val p: kotlin.collections.List<kotlin.Float>? = null,

    /* List of timestamp in UNIX ms. */
    @Json(name = "t")
    val t: kotlin.collections.List<kotlin.Long>? = null,

    /* List of values showing the side (Buy/sell) of each trade. List of supported values: <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\",>here</a> */
    @Json(name = "si")
    val si: kotlin.collections.List<kotlin.String>? = null,

    /* List of values showing the counterparty of each trade. List of supported values: <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\",>here</a> */
    @Json(name = "cp")
    val cp: kotlin.collections.List<kotlin.String>? = null,

    /* List of trade conditions. A comprehensive list of trade conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\">here</a> */
    @Json(name = "c")
    val c: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

