/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param isin ISIN.
 * @param cusip Cusip.
 * @param figi FIGI.
 * @param coupon Coupon.
 * @param maturityDate Period.
 * @param offeringPrice Offering price.
 * @param issueDate Issue date.
 * @param bondType Bond type.
 * @param debtType Bond type.
 * @param industryGroup Industry.
 * @param industrySubGroup Sub-Industry.
 * @param asset Asset.
 * @param assetType Asset.
 * @param datedDate Dated date.
 * @param firstCouponDate First coupon date.
 * @param originalOffering Offering amount.
 * @param amountOutstanding Outstanding amount.
 * @param paymentFrequency Payment frequency.
 * @param securityLevel Security level.
 * @param callable Callable.
 * @param couponType Coupon type.
 */

data class BondProfile (

    /* ISIN. */
    @Json(name = "isin")
    val isin: kotlin.String? = null,

    /* Cusip. */
    @Json(name = "cusip")
    val cusip: kotlin.String? = null,

    /* FIGI. */
    @Json(name = "figi")
    val figi: kotlin.String? = null,

    /* Coupon. */
    @Json(name = "coupon")
    val coupon: kotlin.Float? = null,

    /* Period. */
    @Json(name = "maturityDate")
    val maturityDate: kotlin.String? = null,

    /* Offering price. */
    @Json(name = "offeringPrice")
    val offeringPrice: kotlin.Float? = null,

    /* Issue date. */
    @Json(name = "issueDate")
    val issueDate: kotlin.String? = null,

    /* Bond type. */
    @Json(name = "bondType")
    val bondType: kotlin.String? = null,

    /* Bond type. */
    @Json(name = "debtType")
    val debtType: kotlin.String? = null,

    /* Industry. */
    @Json(name = "industryGroup")
    val industryGroup: kotlin.String? = null,

    /* Sub-Industry. */
    @Json(name = "industrySubGroup")
    val industrySubGroup: kotlin.String? = null,

    /* Asset. */
    @Json(name = "asset")
    val asset: kotlin.String? = null,

    /* Asset. */
    @Json(name = "assetType")
    val assetType: kotlin.String? = null,

    /* Dated date. */
    @Json(name = "datedDate")
    val datedDate: kotlin.String? = null,

    /* First coupon date. */
    @Json(name = "firstCouponDate")
    val firstCouponDate: kotlin.String? = null,

    /* Offering amount. */
    @Json(name = "originalOffering")
    val originalOffering: kotlin.Float? = null,

    /* Outstanding amount. */
    @Json(name = "amountOutstanding")
    val amountOutstanding: kotlin.Float? = null,

    /* Payment frequency. */
    @Json(name = "paymentFrequency")
    val paymentFrequency: kotlin.String? = null,

    /* Security level. */
    @Json(name = "securityLevel")
    val securityLevel: kotlin.String? = null,

    /* Callable. */
    @Json(name = "callable")
    val callable: kotlin.Boolean? = null,

    /* Coupon type. */
    @Json(name = "couponType")
    val couponType: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

