/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol symbol
 * @param totalESGScore Total ESG Score
 * @param environmentScore symbol
 * @param governanceScore symbol
 * @param socialScore symbol
 * @param `data` 
 */

data class CompanyESG (

    /* symbol */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Total ESG Score */
    @Json(name = "totalESGScore")
    val totalESGScore: kotlin.Float? = null,

    /* symbol */
    @Json(name = "environmentScore")
    val environmentScore: kotlin.Float? = null,

    /* symbol */
    @Json(name = "governanceScore")
    val governanceScore: kotlin.Float? = null,

    /* symbol */
    @Json(name = "socialScore")
    val socialScore: kotlin.Float? = null,

    @Json(name = "data")
    val `data`: kotlin.Any? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

