/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param period Period
 * @param growth Growth Score
 * @param profitability Profitability Score
 * @param cashGenerationCapitalAllocation Cash Generation and Capital Allocation
 * @param leverage Leverage Score
 * @param score Total Score
 * @param letterScore Letter Score
 */

data class CompanyEarningsQualityScoreData (

    /* Period */
    @Json(name = "period")
    val period: kotlin.String? = null,

    /* Growth Score */
    @Json(name = "growth")
    val growth: kotlin.Float? = null,

    /* Profitability Score */
    @Json(name = "profitability")
    val profitability: kotlin.Float? = null,

    /* Cash Generation and Capital Allocation */
    @Json(name = "cashGenerationCapitalAllocation")
    val cashGenerationCapitalAllocation: kotlin.Float? = null,

    /* Leverage Score */
    @Json(name = "leverage")
    val leverage: kotlin.Float? = null,

    /* Total Score */
    @Json(name = "score")
    val score: kotlin.Float? = null,

    /* Letter Score */
    @Json(name = "letterScore")
    val letterScore: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

