/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param name Executive name
 * @param age Age
 * @param title Title
 * @param since Year appointed
 * @param sex Sex
 * @param compensation Total compensation
 * @param currency Compensation currency
 */

@Serializable
data class Company (
    /* Executive name */
    @SerialName("name")
    val name: String? = null,
    /* Age */
    @SerialName("age")
    val age: Long? = null,
    /* Title */
    @SerialName("title")
    val title: String? = null,
    /* Year appointed */
    @SerialName("since")
    val since: String? = null,
    /* Sex */
    @SerialName("sex")
    val sex: String? = null,
    /* Total compensation */
    @SerialName("compensation")
    val compensation: Long? = null,
    /* Compensation currency */
    @SerialName("currency")
    val currency: String? = null
) {
	companion object {
    }
}

