/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param name Executive name
 * @param age Age
 * @param title Title
 * @param since Year appointed
 * @param sex Sex
 * @param compensation Total compensation
 * @param currency Compensation currency
 */

data class Company (

    /* Executive name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Age */
    @Json(name = "age")
    val age: kotlin.Long? = null,

    /* Title */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Year appointed */
    @Json(name = "since")
    val since: kotlin.String? = null,

    /* Sex */
    @Json(name = "sex")
    val sex: kotlin.String? = null,

    /* Total compensation */
    @Json(name = "compensation")
    val compensation: kotlin.Long? = null,

    /* Compensation currency */
    @Json(name = "currency")
    val currency: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

