/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param o List of open prices for returned candles.
 * @param h List of high prices for returned candles.
 * @param l List of low prices for returned candles.
 * @param c List of close prices for returned candles.
 * @param v List of volume data for returned candles.
 * @param t List of timestamp for returned candles.
 * @param s Status of the response. This field can either be ok or no_data.
 */

@Serializable
data class CryptoCandles (
    /* List of open prices for returned candles. */
    @SerialName("o")
    val o: List<Float>? = null,
    /* List of high prices for returned candles. */
    @SerialName("h")
    val h: List<Float>? = null,
    /* List of low prices for returned candles. */
    @SerialName("l")
    val l: List<Float>? = null,
    /* List of close prices for returned candles. */
    @SerialName("c")
    val c: List<Float>? = null,
    /* List of volume data for returned candles. */
    @SerialName("v")
    val v: List<Float>? = null,
    /* List of timestamp for returned candles. */
    @SerialName("t")
    val t: List<Long>? = null,
    /* Status of the response. This field can either be ok or no_data. */
    @SerialName("s")
    val s: String? = null
) {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

