/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.EarningRelease

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param earningsCalendar Array of earnings release.
 */

data class EarningsCalendar (

    /* Array of earnings release. */
    @Json(name = "earningsCalendar")
    val earningsCalendar: kotlin.collections.List<EarningRelease>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

