/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol.
 * @param event Event name.
 * @param time Date time in UTC.
 * @param year Earnings year.
 * @param quarter Earnings quarter.
 * @param liveAudio Live audio streaming file.
 * @param recording Recoding in mp3 format.
 */

data class EarningsCallLiveResult (

    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Event name. */
    @Json(name = "event")
    val event: kotlin.String? = null,

    /* Date time in UTC. */
    @Json(name = "time")
    val time: kotlin.String? = null,

    /* Earnings year. */
    @Json(name = "year")
    val year: kotlin.Long? = null,

    /* Earnings quarter. */
    @Json(name = "quarter")
    val quarter: kotlin.Long? = null,

    /* Live audio streaming file. */
    @Json(name = "liveAudio")
    val liveAudio: kotlin.String? = null,

    /* Recoding in mp3 format. */
    @Json(name = "recording")
    val recording: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

