/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.EarningsCallLiveResult

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param event Array of earnings call events that support live streaming.
 */

data class EarningsCallLive (

    /* Array of earnings call events that support live streaming. */
    @Json(name = "event")
    val event: kotlin.collections.List<EarningsCallLiveResult>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

