/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param epsAvg Average EPS estimates including Finnhub's proprietary estimates.
 * @param epsHigh Highest estimate.
 * @param epsLow Lowest estimate.
 * @param numberAnalysts Number of Analysts.
 * @param period Period.
 */

data class EarningEstimate (
    /* Average EPS estimates including Finnhub's proprietary estimates. */
    @Json(name = "epsAvg")
    val epsAvg: kotlin.Float? = null,
    /* Highest estimate. */
    @Json(name = "epsHigh")
    val epsHigh: kotlin.Float? = null,
    /* Lowest estimate. */
    @Json(name = "epsLow")
    val epsLow: kotlin.Float? = null,
    /* Number of Analysts. */
    @Json(name = "numberAnalysts")
    val numberAnalysts: kotlin.Long? = null,
    /* Period. */
    @Json(name = "period")
    val period: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

