/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param code Finnhub economic code used to get historical data
 * @param country Country
 * @param name Indicator name
 * @param unit Unit
 */

@Serializable
data class EconomicCode (
    /* Finnhub economic code used to get historical data */
    @SerialName("code")
    val code: String? = null,
    /* Country */
    @SerialName("country")
    val country: String? = null,
    /* Indicator name */
    @SerialName("name")
    val name: String? = null,
    /* Unit */
    @SerialName("unit")
    val unit: String? = null
) {
	companion object {
    }

}

