/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param actual Actual release
 * @param prev Previous release
 * @param country Country
 * @param unit Unit
 * @param estimate Estimate
 * @param event Event
 * @param impact Impact level
 * @param time Release time
 */

@Serializable
data class EconomicEvent (
    /* Actual release */
    @SerialName("actual")
    val actual: kotlin.Float? = null,
    /* Previous release */
    @SerialName("prev")
    val prev: kotlin.Float? = null,
    /* Country */
    @SerialName("country")
    val country: kotlin.String? = null,
    /* Unit */
    @SerialName("unit")
    val unit: kotlin.String? = null,
    /* Estimate */
    @SerialName("estimate")
    val estimate: kotlin.Float? = null,
    /* Event */
    @SerialName("event")
    val event: kotlin.String? = null,
    /* Impact level */
    @SerialName("impact")
    val impact: kotlin.String? = null,
    /* Release time */
    @SerialName("time")
    val time: kotlin.String? = null
)