/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.finnhub.api.models


import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 *
 * @param data Array of economic data for requested code.
 * @param code Finnhub economic code
 */

@ExperimentalSerializationApi
@Serializable
data class EconomicData(
    /* Array of economic data for requested code. */
    @SerialName("data")
    val data: List<JsonObject>? = null,
    /* Finnhub economic code */
    @SerialName("code")
    val code: String? = null
) {
    companion object {
    }

}

