/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param `actual` Actual release
 * @param prev Previous release
 * @param country Country
 * @param unit Unit
 * @param estimate Estimate
 * @param event Event
 * @param impact Impact level
 * @param time Release time
 */

data class EconomicEvent (

    /* Actual release */
    @Json(name = "actual")
    val `actual`: kotlin.Float? = null,

    /* Previous release */
    @Json(name = "prev")
    val prev: kotlin.Float? = null,

    /* Country */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Unit */
    @Json(name = "unit")
    val unit: kotlin.String? = null,

    /* Estimate */
    @Json(name = "estimate")
    val estimate: kotlin.Float? = null,

    /* Event */
    @Json(name = "event")
    val event: kotlin.String? = null,

    /* Impact level */
    @Json(name = "impact")
    val impact: kotlin.String? = null,

    /* Release time */
    @Json(name = "time")
    val time: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

