/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param code Finnhub economic code used to get historical data
 * @param country Country
 * @param name Indicator name
 * @param unit Unit
 */

data class EconomicCode (

    /* Finnhub economic code used to get historical data */
    @Json(name = "code")
    val code: kotlin.String? = null,

    /* Country */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Indicator name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Unit */
    @Json(name = "unit")
    val unit: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

