/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param revenueAvg Average revenue estimates.
 * @param revenueHigh Highest estimate.
 * @param revenueLow Lowest estimate.
 * @param numberAnalysts Number of Analysts.
 * @param period Period.
 */

@Serializable
data class Estimate (
    /* Average revenue estimates. */
    @SerialName("revenueAvg")
    val revenueAvg: Long? = null,
    /* Highest estimate. */
    @SerialName("revenueHigh")
    val revenueHigh: Long? = null,
    /* Lowest estimate. */
    @SerialName("revenueLow")
    val revenueLow: Long? = null,
    /* Number of Analysts. */
    @SerialName("numberAnalysts")
    val numberAnalysts: Long? = null,
    /* Period. */
    @SerialName("period")
    val period: String? = null
) {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

