/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param name Name
 * @param assetClass Asset Class.
 * @param investmentSegment Investment Segment.
 * @param aum AUM.
 * @param nav NAV.
 * @param navCurrency NAV currency.
 * @param expenseRatio Expense ratio.
 * @param trackingIndex Tracking Index.
 * @param etfCompany ETF issuer.
 * @param domicile ETF domicile.
 * @param inceptionDate Inception date.
 * @param website ETF's website.
 * @param isin ISIN.
 * @param cusip CUSIP.
 * @param priceToEarnings P/E.
 * @param priceToBook P/B.
 * @param avgVolume 30-day average volume.
 * @param description ETF's description.
 */

data class ETFProfileData (

    /* Name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Asset Class. */
    @Json(name = "assetClass")
    val assetClass: kotlin.String? = null,

    /* Investment Segment. */
    @Json(name = "investmentSegment")
    val investmentSegment: kotlin.String? = null,

    /* AUM. */
    @Json(name = "aum")
    val aum: kotlin.Float? = null,

    /* NAV. */
    @Json(name = "nav")
    val nav: kotlin.Float? = null,

    /* NAV currency. */
    @Json(name = "navCurrency")
    val navCurrency: kotlin.String? = null,

    /* Expense ratio. */
    @Json(name = "expenseRatio")
    val expenseRatio: kotlin.Float? = null,

    /* Tracking Index. */
    @Json(name = "trackingIndex")
    val trackingIndex: kotlin.String? = null,

    /* ETF issuer. */
    @Json(name = "etfCompany")
    val etfCompany: kotlin.String? = null,

    /* ETF domicile. */
    @Json(name = "domicile")
    val domicile: kotlin.String? = null,

    /* Inception date. */
    @Json(name = "inceptionDate")
    val inceptionDate: kotlin.String? = null,

    /* ETF's website. */
    @Json(name = "website")
    val website: kotlin.String? = null,

    /* ISIN. */
    @Json(name = "isin")
    val isin: kotlin.String? = null,

    /* CUSIP. */
    @Json(name = "cusip")
    val cusip: kotlin.String? = null,

    /* P/E. */
    @Json(name = "priceToEarnings")
    val priceToEarnings: kotlin.Float? = null,

    /* P/B. */
    @Json(name = "priceToBook")
    val priceToBook: kotlin.Float? = null,

    /* 30-day average volume. */
    @Json(name = "avgVolume")
    val avgVolume: kotlin.Float? = null,

    /* ETF's description. */
    @Json(name = "description")
    val description: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

