/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models

import kotlinx.serialization.SerialName
/**
 * 
 * @param industry Industry
 * @param exposure Percent of exposure.
 */

@kotlinx.serialization.Serializable
data class ETFSectorExposureData (
    /* Industry */
    @SerialName("industry")
    val industry: kotlin.String? = null,
    /* Percent of exposure. */
    @SerialName("exposure")
    val exposure: kotlin.String? = null
)

