/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param symbol ETF symbol.
 * @param atDate Holdings update date.
 * @param numberOfHoldings Number of holdings.
 * @param holdings Array of holdings.
 */

data class ETFsHoldings (
    /* ETF symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Holdings update date. */
    @Json(name = "atDate")
    val atDate: kotlin.String? = null,
    /* Number of holdings. */
    @Json(name = "numberOfHoldings")
    val numberOfHoldings: kotlin.Long? = null,
    /* Array of holdings. */
    @Json(name = "holdings")
    val holdings: kotlin.collections.List<kotlin.Any>? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

