/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 *
 * @param symbol ETF symbol.
 * @param countryExposure Array of countries and and exposure levels.
 */

@Serializable
data class ETFsCountryExposure(
    /* ETF symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* Array of countries and and exposure levels. */
    @SerialName("countryExposure")
    val countryExposure: List<JsonObject>? = null
) {
    companion object {
        private const val serialVersionUID: Long = 123
    }
}

