/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param content Highlighted content
 * @param snippetId Location of the content in the rendered document
 * @param startOffset Start offset of highlighted content
 * @param endOffset End offset of highlighted content
 */

data class ExcerptResponse (

    /* Highlighted content */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /* Location of the content in the rendered document */
    @Json(name = "snippetId")
    val snippetId: kotlin.String? = null,

    /* Start offset of highlighted content */
    @Json(name = "startOffset")
    val startOffset: kotlin.String? = null,

    /* End offset of highlighted content */
    @Json(name = "endOffset")
    val endOffset: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

