/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param fromDate Start time of the event in EST.
 * @param toDate End time of the event in EST.
 * @param eventDescription Event's description.
 * @param url URL.
 */

data class FDAComitteeMeeting (

    /* Start time of the event in EST. */
    @Json(name = "fromDate")
    val fromDate: kotlin.String? = null,

    /* End time of the event in EST. */
    @Json(name = "toDate")
    val toDate: kotlin.String? = null,

    /* Event's description. */
    @Json(name = "eventDescription")
    val eventDescription: kotlin.String? = null,

    /* URL. */
    @Json(name = "url")
    val url: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

