/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param negative % of negative words in the filing.
 * @param positive % of positive words in the filing.
 * @param polarity % of polarity words in the filing.
 * @param litigious % of litigious words in the filing.
 * @param uncertainty % of uncertainty words in the filing.
 * @param constraining % of constraining words in the filing.
 * @param modalWeak % of modal-weak words in the filing.
 * @param modalStrong % of modal-strong words in the filing.
 * @param modalModerate % of modal-moderate words in the filing.
 */

data class FilingSentiment (

    /* % of negative words in the filing. */
    @Json(name = "negative")
    val negative: kotlin.Float? = null,

    /* % of positive words in the filing. */
    @Json(name = "positive")
    val positive: kotlin.Float? = null,

    /* % of polarity words in the filing. */
    @Json(name = "polarity")
    val polarity: kotlin.Float? = null,

    /* % of litigious words in the filing. */
    @Json(name = "litigious")
    val litigious: kotlin.Float? = null,

    /* % of uncertainty words in the filing. */
    @Json(name = "uncertainty")
    val uncertainty: kotlin.Float? = null,

    /* % of constraining words in the filing. */
    @Json(name = "constraining")
    val constraining: kotlin.Float? = null,

    /* % of modal-weak words in the filing. */
    @Json(name = "modal-weak")
    val modalWeak: kotlin.Float? = null,

    /* % of modal-strong words in the filing. */
    @Json(name = "modal-strong")
    val modalStrong: kotlin.Float? = null,

    /* % of modal-moderate words in the filing. */
    @Json(name = "modal-moderate")
    val modalModerate: kotlin.Float? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

