/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol of the company.
 * @param financials An array of map of key, value pairs containing the data for each period.
 */

data class FinancialStatements (

    /* Symbol of the company. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* An array of map of key, value pairs containing the data for each period. */
    @Json(name = "financials")
    val financials: kotlin.collections.List<kotlin.Any>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

