/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * 
 * @param base Base currency.
 * @param quote 
 */

@Serializable
data class Forexrates (
    /* Base currency. */
    @SerialName("base")
    val base: String? = null,
    @SerialName("quote")
    val quote: JsonObject? = null
) {
	companion object {
    }

}

