/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param name Investor's name.
 * @param share Number of shares held by the investor.
 * @param change Number of share changed (net buy or sell) from the last period.
 * @param filingDate Filing date.
 * @param portfolioPercent Percent of the fund's portfolio comprised of the company's share.
 */

data class FundOwnershipInfo (
    /* Investor's name. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* Number of shares held by the investor. */
    @Json(name = "share")
    val share: kotlin.Long? = null,
    /* Number of share changed (net buy or sell) from the last period. */
    @Json(name = "change")
    val change: kotlin.Long? = null,
    /* Filing date. */
    @Json(name = "filingDate")
    val filingDate: kotlin.String? = null,
    /* Percent of the fund's portfolio comprised of the company's share. */
    @Json(name = "portfolioPercent")
    val portfolioPercent: kotlin.Float? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

