/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param s Symbol.
 * @param skip Number of ticks skipped.
 * @param count Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
 * @param total Total number of ticks for that date.
 * @param av List of Ask volume data.
 * @param a List of Ask price data.
 * @param ax List of venues/exchanges - Ask price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a>
 * @param bv List of Bid volume data.
 * @param b List of Bid price data.
 * @param bx List of venues/exchanges - Bid price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a>
 * @param t List of timestamp in UNIX ms.
 * @param c List of quote conditions. A comprehensive list of quote conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1iiA6e7Osdtai0oPMOUzgAIKXCsay89dFDmsegz6OpEg/edit?usp=sharing\">here</a>
 */

data class HistoricalNBBO (
    /* Symbol. */
    @Json(name = "s")
    val s: kotlin.String? = null,
    /* Number of ticks skipped. */
    @Json(name = "skip")
    val skip: kotlin.Long? = null,
    /* Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned. */
    @Json(name = "count")
    val count: kotlin.Long? = null,
    /* Total number of ticks for that date. */
    @Json(name = "total")
    val total: kotlin.Long? = null,
    /* List of Ask volume data. */
    @Json(name = "av")
    val av: kotlin.collections.List<kotlin.Float>? = null,
    /* List of Ask price data. */
    @Json(name = "a")
    val a: kotlin.collections.List<kotlin.Float>? = null,
    /* List of venues/exchanges - Ask price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a> */
    @Json(name = "ax")
    val ax: kotlin.collections.List<kotlin.String>? = null,
    /* List of Bid volume data. */
    @Json(name = "bv")
    val bv: kotlin.collections.List<kotlin.Float>? = null,
    /* List of Bid price data. */
    @Json(name = "b")
    val b: kotlin.collections.List<kotlin.Float>? = null,
    /* List of venues/exchanges - Bid price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a> */
    @Json(name = "bx")
    val bx: kotlin.collections.List<kotlin.String>? = null,
    /* List of timestamp in UNIX ms. */
    @Json(name = "t")
    val t: kotlin.collections.List<kotlin.Long>? = null,
    /* List of quote conditions. A comprehensive list of quote conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1iiA6e7Osdtai0oPMOUzgAIKXCsay89dFDmsegz6OpEg/edit?usp=sharing\">here</a> */
    @Json(name = "c")
    val c: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

