/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param buy Number of buy signals
 * @param neutral Number of neutral signals
 * @param sell Number of sell signals
 */

@Serializable
data class Indicator (
    /* Number of buy signals */
    @SerialName("buy")
    val buy: Long? = null,
    /* Number of neutral signals */
    @SerialName("neutral")
    val neutral: Long? = null,
    /* Number of sell signals */
    @SerialName("sell")
    val sell: Long? = null
) {
	companion object {
    }

}

