/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol.
 * @param name Name.
 * @param isin ISIN.
 * @param cusip Cusip.
 * @param shareClassFIGI Global Share Class FIGI.
 * @param weight Weight.
 */

data class IndicesConstituentsBreakdown (

    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* ISIN. */
    @Json(name = "isin")
    val isin: kotlin.String? = null,

    /* Cusip. */
    @Json(name = "cusip")
    val cusip: kotlin.String? = null,

    /* Global Share Class FIGI. */
    @Json(name = "shareClassFIGI")
    val shareClassFIGI: kotlin.String? = null,

    /* Weight. */
    @Json(name = "weight")
    val weight: kotlin.Float? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

