/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.DocumentResponse

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param filingId Filing Id in Alpharesearch platform
 * @param title Filing title
 * @param filerId Id of the entity submitted the filing
 * @param symbol List of symbol associate with this filing
 * @param name Filer name
 * @param acceptanceDate Date the filing is submitted.
 * @param filedDate Date the filing is make available to the public
 * @param reportDate Date as which the filing is reported
 * @param form Filing Form
 * @param amend Amendment
 * @param source Filing Source
 * @param pageCount Estimate number of page when printing
 * @param documentCount Number of document in this filing
 * @param documents Document for this filing.
 */

data class InFilingResponse (

    /* Filing Id in Alpharesearch platform */
    @Json(name = "filingId")
    val filingId: kotlin.String? = null,

    /* Filing title */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Id of the entity submitted the filing */
    @Json(name = "filerId")
    val filerId: kotlin.String? = null,

    /* List of symbol associate with this filing */
    @Json(name = "symbol")
    val symbol: kotlin.Any? = null,

    /* Filer name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Date the filing is submitted. */
    @Json(name = "acceptanceDate")
    val acceptanceDate: kotlin.String? = null,

    /* Date the filing is make available to the public */
    @Json(name = "filedDate")
    val filedDate: kotlin.String? = null,

    /* Date as which the filing is reported */
    @Json(name = "reportDate")
    val reportDate: kotlin.String? = null,

    /* Filing Form */
    @Json(name = "form")
    val form: kotlin.String? = null,

    /* Amendment */
    @Json(name = "amend")
    val amend: kotlin.Boolean? = null,

    /* Filing Source */
    @Json(name = "source")
    val source: kotlin.String? = null,

    /* Estimate number of page when printing */
    @Json(name = "pageCount")
    val pageCount: kotlin.Int? = null,

    /* Number of document in this filing */
    @Json(name = "documentCount")
    val documentCount: kotlin.Int? = null,

    /* Document for this filing. */
    @Json(name = "documents")
    val documents: kotlin.collections.List<DocumentResponse>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

