/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param cik Investor's company CIK.
 * @param firmType Firm type.
 * @param manager Manager.
 * @param philosophy Investing philosophy.
 * @param profile Profile info.
 * @param profileImg Profile image.
 */

data class InstitutionalProfileInfo (

    /* Investor's company CIK. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,

    /* Firm type. */
    @Json(name = "firmType")
    val firmType: kotlin.String? = null,

    /* Manager. */
    @Json(name = "manager")
    val manager: kotlin.String? = null,

    /* Investing philosophy. */
    @Json(name = "philosophy")
    val philosophy: kotlin.String? = null,

    /* Profile info. */
    @Json(name = "profile")
    val profile: kotlin.String? = null,

    /* Profile image. */
    @Json(name = "profileImg")
    val profileImg: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

