/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.InstitutionalPortfolioGroup

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param name Investor's name.
 * @param cik CIK.
 * @param `data` Array of positions.
 */

data class InstitutionalPortfolio (

    /* Investor's name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* CIK. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,

    /* Array of positions. */
    @Json(name = "data")
    val `data`: kotlin.collections.List<InstitutionalPortfolioGroup>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

