/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param cik Investor's company CIK.
 * @param name Firm's name.
 * @param putCall <code>put</code> or <code>call</code> for options.
 * @param change Number of shares change.
 * @param noVoting Number of shares with no voting rights.
 * @param percentage Percentage of portfolio.
 * @param share News score.
 * @param sharedVoting Number of shares with shared voting rights.
 * @param soleVoting Number of shares with sole voting rights.
 * @param `value` Position value.
 */

data class InstitutionalOwnershipInfo (

    /* Investor's company CIK. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,

    /* Firm's name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* <code>put</code> or <code>call</code> for options. */
    @Json(name = "putCall")
    val putCall: kotlin.String? = null,

    /* Number of shares change. */
    @Json(name = "change")
    val change: kotlin.Float? = null,

    /* Number of shares with no voting rights. */
    @Json(name = "noVoting")
    val noVoting: kotlin.Float? = null,

    /* Percentage of portfolio. */
    @Json(name = "percentage")
    val percentage: kotlin.Float? = null,

    /* News score. */
    @Json(name = "share")
    val share: kotlin.Float? = null,

    /* Number of shares with shared voting rights. */
    @Json(name = "sharedVoting")
    val sharedVoting: kotlin.Float? = null,

    /* Number of shares with sole voting rights. */
    @Json(name = "soleVoting")
    val soleVoting: kotlin.Float? = null,

    /* Position value. */
    @Json(name = "value")
    val `value`: kotlin.Float? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

