/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol.
 * @param companyName Company name.
 * @param filedDate Filed date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param category Category.
 * @param title Document's title.
 * @param description Document's description.
 * @param url Url.
 * @param language Language.
 * @param country Country.
 */

data class InternationalFiling (

    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Company name. */
    @Json(name = "companyName")
    val companyName: kotlin.String? = null,

    /* Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "filedDate")
    val filedDate: kotlin.String? = null,

    /* Category. */
    @Json(name = "category")
    val category: kotlin.String? = null,

    /* Document's title. */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Document's description. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Url. */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* Language. */
    @Json(name = "language")
    val language: kotlin.String? = null,

    /* Country. */
    @Json(name = "country")
    val country: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

