/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param symbol Symbol
 * @param name Name
 * @param customer Whether the company is a customer.
 * @param supplier Whether the company is a supplier
 */

data class KeyCustomersSuppliers (
    /* Symbol */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Name */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* Whether the company is a customer. */
    @Json(name = "customer")
    val customer: kotlin.Boolean? = null,
    /* Whether the company is a supplier */
    @Json(name = "supplier")
    val supplier: kotlin.Boolean? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

