/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol
 * @param name Name
 * @param customer Whether the company is a customer.
 * @param supplier Whether the company is a supplier
 * @param oneMonthCorrelation 1-month price correlation
 * @param oneYearCorrelation 1-year price correlation
 * @param sixMonthCorrelation 6-month price correlation
 * @param threeMonthCorrelation 3-month price correlation
 * @param twoWeekCorrelation 2-week price correlation
 * @param twoYearCorrelation 2-year price correlation
 */

data class KeyCustomersSuppliers (

    /* Symbol */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Whether the company is a customer. */
    @Json(name = "customer")
    val customer: kotlin.Boolean? = null,

    /* Whether the company is a supplier */
    @Json(name = "supplier")
    val supplier: kotlin.Boolean? = null,

    /* 1-month price correlation */
    @Json(name = "oneMonthCorrelation")
    val oneMonthCorrelation: kotlin.Float? = null,

    /* 1-year price correlation */
    @Json(name = "oneYearCorrelation")
    val oneYearCorrelation: kotlin.Float? = null,

    /* 6-month price correlation */
    @Json(name = "sixMonthCorrelation")
    val sixMonthCorrelation: kotlin.Float? = null,

    /* 3-month price correlation */
    @Json(name = "threeMonthCorrelation")
    val threeMonthCorrelation: kotlin.Float? = null,

    /* 2-week price correlation */
    @Json(name = "twoWeekCorrelation")
    val twoWeekCorrelation: kotlin.Float? = null,

    /* 2-year price correlation */
    @Json(name = "twoYearCorrelation")
    val twoYearCorrelation: kotlin.Float? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

