/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param b Bid price.
 * @param a Ask price.
 * @param bv Bid volume.
 * @param av Ask volume.
 * @param t Reference UNIX timestamp in ms.
 */

data class LastBidMinusAsk (
    /* Bid price. */
    @Json(name = "b")
    val b: kotlin.Float? = null,
    /* Ask price. */
    @Json(name = "a")
    val a: kotlin.Float? = null,
    /* Bid volume. */
    @Json(name = "bv")
    val bv: kotlin.Float? = null,
    /* Ask volume. */
    @Json(name = "av")
    val av: kotlin.Float? = null,
    /* Reference UNIX timestamp in ms. */
    @Json(name = "t")
    val t: kotlin.Long? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

