/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol.
 * @param name Company's name.
 * @param description Description.
 * @param country Country.
 * @param year Year.
 * @param period Period.
 * @param income Income reported by lobbying firms.
 * @param expenses Expenses reported by the company.
 * @param documentUrl Document's URL.
 * @param postedName Posted name.
 * @param date Date.
 * @param clientId Client ID.
 * @param registrantId Registrant ID.
 * @param senateId Senate ID.
 * @param houseregistrantId House registrant ID.
 */

data class LobbyingData (

    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Company's name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Description. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Country. */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Year. */
    @Json(name = "year")
    val year: kotlin.Long? = null,

    /* Period. */
    @Json(name = "period")
    val period: kotlin.String? = null,

    /* Income reported by lobbying firms. */
    @Json(name = "income")
    val income: kotlin.Float? = null,

    /* Expenses reported by the company. */
    @Json(name = "expenses")
    val expenses: kotlin.Float? = null,

    /* Document's URL. */
    @Json(name = "documentUrl")
    val documentUrl: kotlin.String? = null,

    /* Posted name. */
    @Json(name = "postedName")
    val postedName: kotlin.String? = null,

    /* Date. */
    @Json(name = "date")
    val date: kotlin.String? = null,

    /* Client ID. */
    @Json(name = "clientId")
    val clientId: kotlin.String? = null,

    /* Registrant ID. */
    @Json(name = "registrantId")
    val registrantId: kotlin.String? = null,

    /* Senate ID. */
    @Json(name = "senateId")
    val senateId: kotlin.String? = null,

    /* House registrant ID. */
    @Json(name = "houseregistrantId")
    val houseregistrantId: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

