/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.MarketHolidayData

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param timezone Timezone.
 * @param exchange Exchange.
 * @param `data` Array of holidays.
 */

data class MarketHoliday (

    /* Timezone. */
    @Json(name = "timezone")
    val timezone: kotlin.String? = null,

    /* Exchange. */
    @Json(name = "exchange")
    val exchange: kotlin.String? = null,

    /* Array of holidays. */
    @Json(name = "data")
    val `data`: kotlin.collections.List<MarketHolidayData>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

