/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param exchange Exchange.
 * @param timezone Timezone.
 * @param session Market session.
 * @param holiday Holiday event.
 * @param isOpen Whether the market is open at the moment.
 * @param t Current timestamp.
 */

data class MarketStatus (

    /* Exchange. */
    @Json(name = "exchange")
    val exchange: kotlin.String? = null,

    /* Timezone. */
    @Json(name = "timezone")
    val timezone: kotlin.String? = null,

    /* Market session. */
    @Json(name = "session")
    val session: kotlin.String? = null,

    /* Holiday event. */
    @Json(name = "holiday")
    val holiday: kotlin.String? = null,

    /* Whether the market is open at the moment. */
    @Json(name = "isOpen")
    val isOpen: kotlin.Boolean? = null,

    /* Current timestamp. */
    @Json(name = "t")
    val t: kotlin.Long? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

