/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol description
 * @param name Security name
 * @param isin ISIN.
 * @param cusip CUSIP.
 * @param share Number of shares.
 * @param percent Portfolio's percent
 * @param `value` Market value
 * @param assetType Asset type. Can be 1 of the following values: <code>Equity</code>, <code>ETP</code>, <code>Fund</code>, <code>Bond</code>, <code>Other</code> or empty.
 */

data class MutualFundHoldingsData (

    /* Symbol description */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Security name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* ISIN. */
    @Json(name = "isin")
    val isin: kotlin.String? = null,

    /* CUSIP. */
    @Json(name = "cusip")
    val cusip: kotlin.String? = null,

    /* Number of shares. */
    @Json(name = "share")
    val share: kotlin.Float? = null,

    /* Portfolio's percent */
    @Json(name = "percent")
    val percent: kotlin.Float? = null,

    /* Market value */
    @Json(name = "value")
    val `value`: kotlin.Float? = null,

    /* Asset type. Can be 1 of the following values: <code>Equity</code>, <code>ETP</code>, <code>Fund</code>, <code>Bond</code>, <code>Other</code> or empty. */
    @Json(name = "assetType")
    val assetType: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

