/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param buzz 
 * @param companyNewsScore News score.
 * @param sectorAverageBullishPercent Sector average bullish percent.
 * @param sectorAverageNewsScore Sectore average score.
 * @param sentiment 
 * @param symbol Requested symbol.
 */

@Serializable
data class NewsSentiment (
    @SerialName("buzz")
    val buzz: CompanyNewsStatistics? = null,
    /* News score. */
    @SerialName("companyNewsScore")
    val companyNewsScore: Float? = null,
    /* Sector average bullish percent. */
    @SerialName("sectorAverageBullishPercent")
    val sectorAverageBullishPercent: Float? = null,
    /* Sectore average score. */
    @SerialName("sectorAverageNewsScore")
    val sectorAverageNewsScore: Float? = null,
    @SerialName("sentiment")
    val sentiment: Sentiment? = null,
    /* Requested symbol. */
    @SerialName("symbol")
    val symbol: String? = null
) {
	companion object {
    }

}

