/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param category News category.
 * @param datetime Published time in UNIX timestamp.
 * @param headline News headline.
 * @param id News ID. This value can be used for <code>minId</code> params to get the latest news only.
 * @param image Thumbnail image URL.
 * @param related Related stocks and companies mentioned in the article.
 * @param source News source.
 * @param summary News summary.
 * @param url URL of the original article.
 */

data class News (
    /* News category. */
    @Json(name = "category")
    val category: kotlin.String? = null,
    /* Published time in UNIX timestamp. */
    @Json(name = "datetime")
    val datetime: kotlin.Long? = null,
    /* News headline. */
    @Json(name = "headline")
    val headline: kotlin.String? = null,
    /* News ID. This value can be used for <code>minId</code> params to get the latest news only. */
    @Json(name = "id")
    val id: kotlin.Long? = null,
    /* Thumbnail image URL. */
    @Json(name = "image")
    val image: kotlin.String? = null,
    /* Related stocks and companies mentioned in the article. */
    @Json(name = "related")
    val related: kotlin.String? = null,
    /* News source. */
    @Json(name = "source")
    val source: kotlin.String? = null,
    /* News summary. */
    @Json(name = "summary")
    val summary: kotlin.String? = null,
    /* URL of the original article. */
    @Json(name = "url")
    val url: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

