/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.OwnershipInfo

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol of the company.
 * @param ownership Array of investors with detailed information about their holdings.
 */

data class Ownership (

    /* Symbol of the company. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Array of investors with detailed information about their holdings. */
    @Json(name = "ownership")
    val ownership: kotlin.collections.List<OwnershipInfo>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

