/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param quarter Quarter
 * @param year Year
 * @param url Presentation url
 * @param title Title
 * @param atTime At Time.
 */

data class PresentationData (

    /* Quarter */
    @Json(name = "quarter")
    val quarter: kotlin.Long? = null,

    /* Year */
    @Json(name = "year")
    val year: kotlin.Long? = null,

    /* Presentation url */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* Title */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* At Time. */
    @Json(name = "atTime")
    val atTime: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

