/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Company symbol.
 * @param targetHigh Highes analysts' target.
 * @param targetLow Lowest analysts' target.
 * @param targetMean Mean of all analysts' targets.
 * @param targetMedian Median of all analysts' targets.
 * @param lastUpdated Updated time of the data
 */

data class PriceTarget (

    /* Company symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Highes analysts' target. */
    @Json(name = "targetHigh")
    val targetHigh: kotlin.Float? = null,

    /* Lowest analysts' target. */
    @Json(name = "targetLow")
    val targetLow: kotlin.Float? = null,

    /* Mean of all analysts' targets. */
    @Json(name = "targetMean")
    val targetMean: kotlin.Float? = null,

    /* Median of all analysts' targets. */
    @Json(name = "targetMedian")
    val targetMedian: kotlin.Float? = null,

    /* Updated time of the data */
    @Json(name = "lastUpdated")
    val lastUpdated: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

