/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param symbol Company symbol.
 * @param targetHigh Highes analysts' target.
 * @param targetLow Lowest analysts' target.
 * @param targetMean Mean of all analysts' targets.
 * @param targetMedian Median of all analysts' targets.
 * @param lastUpdated Updated time of the data
 */

@Serializable
data class PriceTarget (
    /* Company symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* Highes analysts' target. */
    @SerialName("targetHigh")
    val targetHigh: Float? = null,
    /* Lowest analysts' target. */
    @SerialName("targetLow")
    val targetLow: Float? = null,
    /* Mean of all analysts' targets. */
    @SerialName("targetMean")
    val targetMean: Float? = null,
    /* Median of all analysts' targets. */
    @SerialName("targetMedian")
    val targetMedian: Float? = null,
    /* Updated time of the data */
    @SerialName("lastUpdated")
    val lastUpdated: String? = null
) {
	companion object {
    }

}

