/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param symbol Company symbol.
 * @param buy Number of recommendations that fall into the Buy category
 * @param hold Number of recommendations that fall into the Hold category
 * @param period Updated period
 * @param sell Number of recommendations that fall into the Sell category
 * @param strongBuy Number of recommendations that fall into the Strong Buy category
 * @param strongSell Number of recommendations that fall into the Strong Sell category
 */

@Serializable
data class RecommendationTrend (
    /* Company symbol. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* Number of recommendations that fall into the Buy category */
    @SerialName("buy")
    val buy: Double? = null,
    /* Number of recommendations that fall into the Hold category */
    @SerialName("hold")
    val hold: Double? = null,
    /* Updated period */
    @SerialName("period")
    val period: String? = null,
    /* Number of recommendations that fall into the Sell category */
    @SerialName("sell")
    val sell: Double? = null,
    /* Number of recommendations that fall into the Strong Buy category */
    @SerialName("strongBuy")
    val strongBuy: Double? = null,
    /* Number of recommendations that fall into the Strong Sell category */
    @SerialName("strongSell")
    val strongSell: Double? = null
) {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

