/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param symbol Company symbol.
 * @param buy Number of recommendations that fall into the Buy category
 * @param hold Number of recommendations that fall into the Hold category
 * @param period Updated period
 * @param sell Number of recommendations that fall into the Sell category
 * @param strongBuy Number of recommendations that fall into the Strong Buy category
 * @param strongSell Number of recommendations that fall into the Strong Sell category
 */

data class RecommendationTrend (
    /* Company symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Number of recommendations that fall into the Buy category */
    @Json(name = "buy")
    val buy: kotlin.Long? = null,
    /* Number of recommendations that fall into the Hold category */
    @Json(name = "hold")
    val hold: kotlin.Long? = null,
    /* Updated period */
    @Json(name = "period")
    val period: kotlin.String? = null,
    /* Number of recommendations that fall into the Sell category */
    @Json(name = "sell")
    val sell: kotlin.Long? = null,
    /* Number of recommendations that fall into the Strong Buy category */
    @Json(name = "strongBuy")
    val strongBuy: kotlin.Long? = null,
    /* Number of recommendations that fall into the Strong Sell category */
    @Json(name = "strongSell")
    val strongSell: kotlin.Long? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

