/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param mention Number of mentions
 * @param positiveMention Number of positive mentions
 * @param negativeMention Number of negative mentions
 * @param positiveScore Positive score. Range 0-1
 * @param negativeScore Negative score. Range 0-1
 * @param score Final score. Range: -1 to 1 with 1 is very positive and -1 is very negative
 * @param atTime Period.
 */

data class RedditSentimentContent (

    /* Number of mentions */
    @Json(name = "mention")
    val mention: kotlin.Long? = null,

    /* Number of positive mentions */
    @Json(name = "positiveMention")
    val positiveMention: kotlin.Long? = null,

    /* Number of negative mentions */
    @Json(name = "negativeMention")
    val negativeMention: kotlin.Long? = null,

    /* Positive score. Range 0-1 */
    @Json(name = "positiveScore")
    val positiveScore: kotlin.Float? = null,

    /* Negative score. Range 0-1 */
    @Json(name = "negativeScore")
    val negativeScore: kotlin.Float? = null,

    /* Final score. Range: -1 to 1 with 1 is very positive and -1 is very negative */
    @Json(name = "score")
    val score: kotlin.Float? = null,

    /* Period. */
    @Json(name = "atTime")
    val atTime: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

