/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param accessNumber Access number.
 * @param symbol Symbol.
 * @param cik CIK.
 * @param year Year.
 * @param quarter Quarter.
 * @param form Form type.
 * @param startDate Period start date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param endDate Period end date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param filedDate Filed date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param acceptedDate Accepted date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param report 
 */

data class Report (
    /* Access number. */
    @Json(name = "accessNumber")
    val accessNumber: kotlin.String? = null,
    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* CIK. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,
    /* Year. */
    @Json(name = "year")
    val year: kotlin.Long? = null,
    /* Quarter. */
    @Json(name = "quarter")
    val quarter: kotlin.Long? = null,
    /* Form type. */
    @Json(name = "form")
    val form: kotlin.String? = null,
    /* Period start date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "startDate")
    val startDate: kotlin.String? = null,
    /* Period end date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "endDate")
    val endDate: kotlin.String? = null,
    /* Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "filedDate")
    val filedDate: kotlin.String? = null,
    /* Accepted date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "acceptedDate")
    val acceptedDate: kotlin.String? = null,
    @Json(name = "report")
    val report: kotlin.Any? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

