/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.FilingResponse

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param count Total filing matched your search criteria.
 * @param took Time took to execute your search query on our server, value in ms.
 * @param page Current search page
 * @param filings Filing match your search criteria.
 */

data class SearchResponse (

    /* Total filing matched your search criteria. */
    @Json(name = "count")
    val count: kotlin.Int? = null,

    /* Time took to execute your search query on our server, value in ms. */
    @Json(name = "took")
    val took: kotlin.Int? = null,

    /* Current search page */
    @Json(name = "page")
    val page: kotlin.Int? = null,

    /* Filing match your search criteria. */
    @Json(name = "filings")
    val filings: kotlin.collections.List<FilingResponse>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

