/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.FilingSentiment

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param accessNumber Access number.
 * @param symbol Symbol.
 * @param cik CIK.
 * @param sentiment 
 */

data class SECSentimentAnalysis (

    /* Access number. */
    @Json(name = "accessNumber")
    val accessNumber: kotlin.String? = null,

    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* CIK. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,

    @Json(name = "sentiment")
    val sentiment: FilingSentiment? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

