/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param sector Sector
 * @param metrics Metrics data in key-value format. <code>a</code> and <code>m</code> fields are for average and median respectively.
 */

data class SectorMetricData (

    /* Sector */
    @Json(name = "sector")
    val sector: kotlin.String? = null,

    /* Metrics data in key-value format. <code>a</code> and <code>m</code> fields are for average and median respectively. */
    @Json(name = "metrics")
    val metrics: kotlin.Any? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

