/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.SectorMetricData

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param region Region.
 * @param `data` Metrics for each sector.
 */

data class SectorMetric (

    /* Region. */
    @Json(name = "region")
    val region: kotlin.String? = null,

    /* Metrics for each sector. */
    @Json(name = "data")
    val `data`: kotlin.collections.List<SectorMetricData>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

