/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param cik CIK.
 * @param item1 Cosine similarity of Item 1 (Business). This number is only available for Annual reports.
 * @param item1a Cosine similarity of Item 1A (Risk Factors). This number is available for both Annual and Quarterly reports.
 * @param item2 Cosine similarity of Item 2 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Quarterly reports.
 * @param item7 Cosine similarity of Item 7 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Annual reports.
 * @param item7a Cosine similarity of Item 7A (Quantitative and Qualitative Disclosures About Market Risk). This number is only available for Annual reports.
 * @param accessNumber Access number.
 * @param form Form type.
 * @param filedDate Filed date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param acceptedDate Accepted date <code>%Y-%m-%d %H:%M:%S</code>.
 * @param reportUrl Report's URL.
 * @param filingUrl Filing's URL.
 */

data class SimilarityIndexInfo (
    /* CIK. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,
    /* Cosine similarity of Item 1 (Business). This number is only available for Annual reports. */
    @Json(name = "item1")
    val item1: kotlin.Float? = null,
    /* Cosine similarity of Item 1A (Risk Factors). This number is available for both Annual and Quarterly reports. */
    @Json(name = "item1a")
    val item1a: kotlin.Float? = null,
    /* Cosine similarity of Item 2 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Quarterly reports. */
    @Json(name = "item2")
    val item2: kotlin.Float? = null,
    /* Cosine similarity of Item 7 (Management’s Discussion and Analysis of Financial Condition and Results of Operations). This number is only available for Annual reports. */
    @Json(name = "item7")
    val item7: kotlin.Float? = null,
    /* Cosine similarity of Item 7A (Quantitative and Qualitative Disclosures About Market Risk). This number is only available for Annual reports. */
    @Json(name = "item7a")
    val item7a: kotlin.Float? = null,
    /* Access number. */
    @Json(name = "accessNumber")
    val accessNumber: kotlin.String? = null,
    /* Form type. */
    @Json(name = "form")
    val form: kotlin.String? = null,
    /* Filed date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "filedDate")
    val filedDate: kotlin.String? = null,
    /* Accepted date <code>%Y-%m-%d %H:%M:%S</code>. */
    @Json(name = "acceptedDate")
    val acceptedDate: kotlin.String? = null,
    /* Report's URL. */
    @Json(name = "reportUrl")
    val reportUrl: kotlin.String? = null,
    /* Filing's URL. */
    @Json(name = "filingUrl")
    val filingUrl: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

