/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param symbol Company symbol.
 * @param reddit Reddit sentiment.
 * @param twitter Twitter sentiment.
 */

data class SocialSentiment (
    /* Company symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Reddit sentiment. */
    @Json(name = "reddit")
    val reddit: kotlin.collections.List<kotlin.Any>? = null,
    /* Twitter sentiment. */
    @Json(name = "twitter")
    val twitter: kotlin.collections.List<kotlin.Any>? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

