/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.RedditSentimentContent
import io.finnhub.api.models.TwitterSentimentContent

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Company symbol.
 * @param reddit Reddit sentiment.
 * @param twitter Twitter sentiment.
 */

data class SocialSentiment (

    /* Company symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Reddit sentiment. */
    @Json(name = "reddit")
    val reddit: kotlin.collections.List<RedditSentimentContent>? = null,

    /* Twitter sentiment. */
    @Json(name = "twitter")
    val twitter: kotlin.collections.List<TwitterSentimentContent>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

