/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param description Symbol description
 * @param displaySymbol Display symbol name.
 * @param symbol Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint.
 * @param type Security type.
 * @param currency Price's currency. This might be different from the reporting currency of fundamental data.
 */

@Serializable
data class Stock (
    /* Symbol description */
    @SerialName("description")
    val description: String? = null,
    /* Display symbol name. */
    @SerialName("displaySymbol")
    val displaySymbol: String? = null,
    /* Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint. */
    @SerialName("symbol")
    val symbol: String? = null,
    /* Security type. */
    @SerialName("type")
    val type: String? = null,
    /* Price's currency. This might be different from the reporting currency of fundamental data. */
    @SerialName("currency")
    val currency: String? = null
) {
	companion object {
    }

}

