/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models

import io.finnhub.api.models.KeyCustomersSuppliers

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param symbol symbol
 * @param data Key customers and suppliers.
 */

data class SupplyChainRelationships (
    /* symbol */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Key customers and suppliers. */
    @Json(name = "data")
    val data: kotlin.collections.List<KeyCustomersSuppliers>? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

