/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param atDate Event's date.
 * @param oldSymbol Old symbol.
 * @param newSymbol New symbol.
 */

data class SymbolChangeInfo (

    /* Event's date. */
    @Json(name = "atDate")
    val atDate: kotlin.String? = null,

    /* Old symbol. */
    @Json(name = "oldSymbol")
    val oldSymbol: kotlin.String? = null,

    /* New symbol. */
    @Json(name = "newSymbol")
    val newSymbol: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

