/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.SymbolChangeInfo

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param fromDate From date.
 * @param toDate To date.
 * @param `data` Array of symbol change events.
 */

data class SymbolChange (

    /* From date. */
    @Json(name = "fromDate")
    val fromDate: kotlin.String? = null,

    /* To date. */
    @Json(name = "toDate")
    val toDate: kotlin.String? = null,

    /* Array of symbol change events. */
    @Json(name = "data")
    val `data`: kotlin.collections.List<SymbolChangeInfo>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

