/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.SymbolLookupInfo

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param result Array of search results.
 * @param count Number of results.
 */

data class SymbolLookup (

    /* Array of search results. */
    @Json(name = "result")
    val result: kotlin.collections.List<SymbolLookupInfo>? = null,

    /* Number of results. */
    @Json(name = "count")
    val count: kotlin.Long? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

