/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param description Symbol description
 * @param displaySymbol Display symbol name.
 * @param symbol Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint.
 * @param type Security type.
 */

data class SymbolLookupInfo (
    /* Symbol description */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* Display symbol name. */
    @Json(name = "displaySymbol")
    val displaySymbol: kotlin.String? = null,
    /* Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,
    /* Security type. */
    @Json(name = "type")
    val type: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

