/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models

import io.finnhub.api.models.Indicator

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param count 
 * @param signal Aggregate Signal
 */

data class TechnicalAnalysis (

    @Json(name = "count")
    val count: Indicator? = null,

    /* Aggregate Signal */
    @Json(name = "signal")
    val signal: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

