/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param name Insider's name.
 * @param share Number of shares held after the transaction.
 * @param change Number of share changed from the last period. A positive value suggests a <code>BUY</code> transaction. A negative value suggests a <code>SELL</code> transaction.
 * @param filingDate Filing date.
 * @param transactionDate Transaction date.
 * @param transactionPrice Average transaction price.
 * @param transactionCode Transaction code. A list of codes and their meanings can be found <a href=\"https://www.sec.gov/about/forms/form4data.pdf\" target=\"_blank\" rel=\"noopener\">here</a>.
 */

data class Transactions (
    /* Insider's name. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* Number of shares held after the transaction. */
    @Json(name = "share")
    val share: kotlin.Long? = null,
    /* Number of share changed from the last period. A positive value suggests a <code>BUY</code> transaction. A negative value suggests a <code>SELL</code> transaction. */
    @Json(name = "change")
    val change: kotlin.Long? = null,
    /* Filing date. */
    @Json(name = "filingDate")
    val filingDate: kotlin.String? = null,
    /* Transaction date. */
    @Json(name = "transactionDate")
    val transactionDate: kotlin.String? = null,
    /* Average transaction price. */
    @Json(name = "transactionPrice")
    val transactionPrice: kotlin.Float? = null,
    /* Transaction code. A list of codes and their meanings can be found <a href=\"https://www.sec.gov/about/forms/form4data.pdf\" target=\"_blank\" rel=\"noopener\">here</a>. */
    @Json(name = "transactionCode")
    val transactionCode: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

