/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 * @param name Speaker's name
 * @param speech Speaker's speech
 */

@Serializable
data class TranscriptContent (
    /* Speaker's name */
    @SerialName("name")
    val name: String? = null,
    /* Speaker's speech */
    @SerialName("speech")
    val speech: List<String>? = null
) {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

