/**
* Finnhub API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param adx ADX reading
 * @param trending Whether market is trending or going sideway
 */

data class Trend (
    /* ADX reading */
    @Json(name = "adx")
    val adx: kotlin.Float? = null,
    /* Whether market is trending or going sideway */
    @Json(name = "trending")
    val trending: kotlin.Boolean? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

