/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Company symbol.
 * @param gradeTime Upgrade/downgrade time in UNIX timestamp.
 * @param fromGrade From grade.
 * @param toGrade To grade.
 * @param company Company/analyst who did the upgrade/downgrade.
 * @param action Action can take any of the following values: <code>up(upgrade), down(downgrade), main(maintains), init(initiate), reit(reiterate)</code>.
 */

data class UpgradeDowngrade (

    /* Company symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Upgrade/downgrade time in UNIX timestamp. */
    @Json(name = "gradeTime")
    val gradeTime: kotlin.Long? = null,

    /* From grade. */
    @Json(name = "fromGrade")
    val fromGrade: kotlin.String? = null,

    /* To grade. */
    @Json(name = "toGrade")
    val toGrade: kotlin.String? = null,

    /* Company/analyst who did the upgrade/downgrade. */
    @Json(name = "company")
    val company: kotlin.String? = null,

    /* Action can take any of the following values: <code>up(upgrade), down(downgrade), main(maintains), init(initiate), reit(reiterate)</code>. */
    @Json(name = "action")
    val action: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

