/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param symbol Symbol.
 * @param recipientName Company's name.
 * @param recipientParentName Company's name.
 * @param awardDescription Description.
 * @param country Recipient's country.
 * @param actionDate Period.
 * @param totalValue Income reported by lobbying firms.
 * @param performanceStartDate Performance start date.
 * @param performanceEndDate Performance end date.
 * @param awardingAgencyName Award agency.
 * @param awardingSubAgencyName Award sub-agency.
 * @param awardingOfficeName Award office name.
 * @param performanceCountry Performance country.
 * @param performanceCity Performance city.
 * @param performanceCounty Performance county.
 * @param performanceState Performance state.
 * @param performanceZipCode Performance zip code.
 * @param performanceCongressionalDistrict Performance congressional district.
 * @param naicsCode NAICS code.
 * @param permalink Permalink.
 */

data class UsaSpending (

    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Company's name. */
    @Json(name = "recipientName")
    val recipientName: kotlin.String? = null,

    /* Company's name. */
    @Json(name = "recipientParentName")
    val recipientParentName: kotlin.String? = null,

    /* Description. */
    @Json(name = "awardDescription")
    val awardDescription: kotlin.String? = null,

    /* Recipient's country. */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Period. */
    @Json(name = "actionDate")
    val actionDate: kotlin.String? = null,

    /* Income reported by lobbying firms. */
    @Json(name = "totalValue")
    val totalValue: kotlin.Float? = null,

    /* Performance start date. */
    @Json(name = "performanceStartDate")
    val performanceStartDate: kotlin.String? = null,

    /* Performance end date. */
    @Json(name = "performanceEndDate")
    val performanceEndDate: kotlin.String? = null,

    /* Award agency. */
    @Json(name = "awardingAgencyName")
    val awardingAgencyName: kotlin.String? = null,

    /* Award sub-agency. */
    @Json(name = "awardingSubAgencyName")
    val awardingSubAgencyName: kotlin.String? = null,

    /* Award office name. */
    @Json(name = "awardingOfficeName")
    val awardingOfficeName: kotlin.String? = null,

    /* Performance country. */
    @Json(name = "performanceCountry")
    val performanceCountry: kotlin.String? = null,

    /* Performance city. */
    @Json(name = "performanceCity")
    val performanceCity: kotlin.String? = null,

    /* Performance county. */
    @Json(name = "performanceCounty")
    val performanceCounty: kotlin.String? = null,

    /* Performance state. */
    @Json(name = "performanceState")
    val performanceState: kotlin.String? = null,

    /* Performance zip code. */
    @Json(name = "performanceZipCode")
    val performanceZipCode: kotlin.String? = null,

    /* Performance congressional district. */
    @Json(name = "performanceCongressionalDistrict")
    val performanceCongressionalDistrict: kotlin.String? = null,

    /* NAICS code. */
    @Json(name = "naicsCode")
    val naicsCode: kotlin.String? = null,

    /* Permalink. */
    @Json(name = "permalink")
    val permalink: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

