/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param applicationNumber Application Number.
 * @param companyFilingName Array of companies' name on the patent.
 * @param filingDate Filing date.
 * @param description Description.
 * @param filingStatus Filing status.
 * @param patentNumber Patent number.
 * @param publicationDate Filing date.
 * @param patentType Patent's type.
 * @param url URL of the original article.
 */

data class UsptoPatent (

    /* Application Number. */
    @Json(name = "applicationNumber")
    val applicationNumber: kotlin.String? = null,

    /* Array of companies' name on the patent. */
    @Json(name = "companyFilingName")
    val companyFilingName: kotlin.collections.List<kotlin.String>? = null,

    /* Filing date. */
    @Json(name = "filingDate")
    val filingDate: kotlin.String? = null,

    /* Description. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Filing status. */
    @Json(name = "filingStatus")
    val filingStatus: kotlin.String? = null,

    /* Patent number. */
    @Json(name = "patentNumber")
    val patentNumber: kotlin.String? = null,

    /* Filing date. */
    @Json(name = "publicationDate")
    val publicationDate: kotlin.String? = null,

    /* Patent's type. */
    @Json(name = "patentType")
    val patentType: kotlin.String? = null,

    /* URL of the original article. */
    @Json(name = "url")
    val url: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

