/**
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.finnhub.api.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param year Year.
 * @param quarter Quarter.
 * @param symbol Symbol.
 * @param caseNumber Case number.
 * @param caseStatus Case status.
 * @param receivedDate Received date.
 * @param visaClass Visa class.
 * @param jobTitle Job Title.
 * @param socCode SOC Code. A list of SOC code can be found <a href=\"https://www.bls.gov/oes/current/oes_stru.htm\" target=\"_blank\">here</a>.
 * @param fullTimePosition Full-time position flag.
 * @param beginDate Job's start date.
 * @param endDate Job's end date.
 * @param employerName Company's name.
 * @param worksiteAddress Worksite address.
 * @param worksiteCity Worksite city.
 * @param worksiteCounty Worksite county.
 * @param worksiteState Worksite state.
 * @param worksitePostalCode Worksite postal code.
 * @param wageRangeFrom Wage range from.
 * @param wageRangeTo Wage range to.
 * @param wageUnitOfPay Wage unit of pay.
 * @param wageLevel Wage level.
 * @param h1bDependent H1B dependent flag.
 */

data class VisaApplication (

    /* Year. */
    @Json(name = "year")
    val year: kotlin.Long? = null,

    /* Quarter. */
    @Json(name = "quarter")
    val quarter: kotlin.Long? = null,

    /* Symbol. */
    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    /* Case number. */
    @Json(name = "caseNumber")
    val caseNumber: kotlin.String? = null,

    /* Case status. */
    @Json(name = "caseStatus")
    val caseStatus: kotlin.String? = null,

    /* Received date. */
    @Json(name = "receivedDate")
    val receivedDate: kotlin.String? = null,

    /* Visa class. */
    @Json(name = "visaClass")
    val visaClass: kotlin.String? = null,

    /* Job Title. */
    @Json(name = "jobTitle")
    val jobTitle: kotlin.String? = null,

    /* SOC Code. A list of SOC code can be found <a href=\"https://www.bls.gov/oes/current/oes_stru.htm\" target=\"_blank\">here</a>. */
    @Json(name = "socCode")
    val socCode: kotlin.String? = null,

    /* Full-time position flag. */
    @Json(name = "fullTimePosition")
    val fullTimePosition: kotlin.String? = null,

    /* Job's start date. */
    @Json(name = "beginDate")
    val beginDate: kotlin.String? = null,

    /* Job's end date. */
    @Json(name = "endDate")
    val endDate: kotlin.String? = null,

    /* Company's name. */
    @Json(name = "employerName")
    val employerName: kotlin.String? = null,

    /* Worksite address. */
    @Json(name = "worksiteAddress")
    val worksiteAddress: kotlin.String? = null,

    /* Worksite city. */
    @Json(name = "worksiteCity")
    val worksiteCity: kotlin.String? = null,

    /* Worksite county. */
    @Json(name = "worksiteCounty")
    val worksiteCounty: kotlin.String? = null,

    /* Worksite state. */
    @Json(name = "worksiteState")
    val worksiteState: kotlin.String? = null,

    /* Worksite postal code. */
    @Json(name = "worksitePostalCode")
    val worksitePostalCode: kotlin.String? = null,

    /* Wage range from. */
    @Json(name = "wageRangeFrom")
    val wageRangeFrom: kotlin.Float? = null,

    /* Wage range to. */
    @Json(name = "wageRangeTo")
    val wageRangeTo: kotlin.Float? = null,

    /* Wage unit of pay. */
    @Json(name = "wageUnitOfPay")
    val wageUnitOfPay: kotlin.String? = null,

    /* Wage level. */
    @Json(name = "wageLevel")
    val wageLevel: kotlin.String? = null,

    /* H1B dependent flag. */
    @Json(name = "h1bDependent")
    val h1bDependent: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

